[project]
name = "jetblack-memoryqueue"
version = "0.2.0"
description = "An implementation of a memory queue"
authors = [{name = "Rob Blackbourn", email = "rob.blackbourn@gmail.com"}]
readme = "README.md"
requires-python = ">=3.11"

[project.optional-dependencies]
dev = [
    "pytest",
    "mypy",
]
build = [
    "auditwheel",
    "build",
]

[project.urls]
Repository = "https://github.com/rob-blackbourn/jetblack-memoryqueue"

[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
ext-modules = [
    {name = "jetblack_memoryqueue.memoryqueue", sources = ["src/jetblack_memoryqueue/memoryqueue.c"]},
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
jetblack_memoryqueue = ["*.pyi", "py.typed"]

# pytest
[tool.pytest.ini_options]
testpaths = ["tests"]

# mypy
[tool.mypy]
files = [ "src", "tests", "examples" ]

[[tool.mypy.overrides]]
module = "pytest"
ignore_missing_imports = true
