from collections.abc import Iterator
from typing import SupportsIndex, overload

class memoryqueue:
    def __init__(self, *args: bytes | bytearray | memoryview) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: SupportsIndex) -> int: ...
    @overload
    def __getitem__(self, key: slice) -> memoryqueue: ...
    def __bytes__(self) -> bytes: ...
    def __buffer__(self, flags: int) -> memoryview: ...
    def __release_buffer__(self, buffer: memoryview) -> None: ...
    def __iter__(self) -> Iterator[memoryview]: ...
    def __eq__(self, value: object) -> bool: ...
    def __contains__(self, item: bytes | bytearray | memoryview | int) -> bool: ...
    @property
    def _views(self) -> list[memoryview]: ...
    def append(self, buf: bytes | bytearray | memoryview) -> None: ...
    def popleft(self) -> memoryview: ...
    def clear(self) -> None: ...
    @classmethod
    def equals(cls, lhs: memoryqueue, rhs: memoryqueue) -> bool: ...
    def find(self, item: bytes | bytearray | memoryview, i: int | None = None, j: int | None = None) -> int: ...
    def index(self, item: bytes | bytearray | memoryview, i: int | None = None, j: int | None = None) -> int: ...
